// Generated by BUCKLESCRIPT VERSION 1.9.0, PLEASE EDIT WITH CARE
'use strict';

var Curry            = require("bs-platform/lib/js/curry.js");
var App$BsSentiaStd  = require("../src/app.js");
var Func$BsSentiaStd = require("../src/func.js");
var Task$BsSentiaStd = require("../src/task.js");

var delayedInc = App$BsSentiaStd.Cmd[/* fromTask */2](Task$BsSentiaStd.map((function (param) {
            return Func$BsSentiaStd.always(/* Inc */0, param);
          }), Task$BsSentiaStd.delay(3000)));

function update(action, state) {
  if (action !== 0) {
    return /* tuple */[
            state,
            App$BsSentiaStd.Cmd[/* none */0]
          ];
  } else {
    return /* tuple */[
            state + 1 | 0,
            delayedInc
          ];
  }
}

App$BsSentiaStd.make(0, update, (function (state, _) {
        console.log(state);
        return /* () */0;
      }), /* Some */[(function () {
          console.log("ACTION");
          return /* () */0;
        })], /* None */0, /* Some */[(function (_, dispatch) {
          return Curry._1(dispatch, /* Inc */0);
        })], /* () */0);

exports.delayedInc = delayedInc;
exports.update     = update;
/* delayedInc Not a pure module */
