// Generated by BUCKLESCRIPT VERSION 2.0.0, PLEASE EDIT WITH CARE
'use strict';

var Block   = require("bs-platform/lib/js/block.js");
var Curry   = require("bs-platform/lib/js/curry.js");
var Prelude = require("./Prelude.js");

function none() {
  return /* () */0;
}

function make(a, cb) {
  return Curry._1(cb, a);
}

function map(f, a, cb) {
  return Curry._1(a, (function (param) {
                return Prelude.$great$great(f, cb, param);
              }));
}

function flatten(a, cb) {
  return Curry._1(a, (function (b) {
                return Curry._1(b, cb);
              }));
}

function flatMap(f, a) {
  return (function (param) {
      return Curry._1(a, (function (param$1) {
                    return Prelude.$great$great(f, (function (b) {
                                  return Curry._1(b, param);
                                }), param$1);
                  }));
    });
}

function fromPromise(f, cb) {
  Curry._1(f, /* () */0).then((function (a) {
          return Curry._1(cb, /* Ok */Block.__(0, [a]));
        }), (function (err) {
          return Curry._1(cb, /* Error */Block.__(1, [err]));
        }));
  return /* () */0;
}

exports.none        = none;
exports.make        = make;
exports.map         = map;
exports.flatten     = flatten;
exports.flatMap     = flatMap;
exports.fromPromise = fromPromise;
/* No side effect */
