// Generated by BUCKLESCRIPT VERSION 1.9.0, PLEASE EDIT WITH CARE
'use strict';


var App = 0;

var Fun = 0;

var Option = 0;

var Remote = 0;

var Result = 0;

var Task = 0;

exports.App    = App;
exports.Fun    = Fun;
exports.Option = Option;
exports.Remote = Remote;
exports.Result = Result;
exports.Task   = Task;
/* No side effect */
