// Generated by BUCKLESCRIPT VERSION 1.9.0, PLEASE EDIT WITH CARE
'use strict';

var StdGlobal = require("./stdGlobal.js");

var Option = 0;

var Remote = 0;

var Result = 0;

var Task = 0;

var List = 0;

var $$String = 0;

var identity = StdGlobal.identity;

var always = StdGlobal.always;

var $$void = StdGlobal.$$void;

var $great$great = StdGlobal.$great$great;

var flip = StdGlobal.flip;

var curry = StdGlobal.curry;

var uncurry = StdGlobal.uncurry;

var tap = StdGlobal.tap;

exports.Option       = Option;
exports.Remote       = Remote;
exports.Result       = Result;
exports.Task         = Task;
exports.List         = List;
exports.$$String     = $$String;
exports.identity     = identity;
exports.always       = always;
exports.$$void       = $$void;
exports.$great$great = $great$great;
exports.flip         = flip;
exports.curry        = curry;
exports.uncurry      = uncurry;
exports.tap          = tap;
/* No side effect */
