// Generated by BUCKLESCRIPT VERSION 1.9.0, PLEASE EDIT WITH CARE
'use strict';

var List                = require("bs-platform/lib/js/list.js");
var Curry               = require("bs-platform/lib/js/curry.js");
var StdList$BsSentiaStd = require("./stdList.js");

function id(a) {
  return a;
}

function always(a, _) {
  return a;
}

function noOp() {
  return /* () */0;
}

function $great$great(f, g, x) {
  return Curry._1(g, Curry._1(f, x));
}

function flip(f, a, b) {
  return Curry._2(f, b, a);
}

function tap(f, a) {
  Curry._1(f, a);
  return a;
}

StdList$BsSentiaStd.length(/* [] */0);

List.length(/* [] */0);

exports.id           = id;
exports.always       = always;
exports.noOp         = noOp;
exports.$great$great = $great$great;
exports.flip         = flip;
exports.tap          = tap;
/*  Not a pure module */
