// Generated by BUCKLESCRIPT VERSION 1.9.0, PLEASE EDIT WITH CARE
'use strict';

var Block = require("bs-platform/lib/js/block.js");
var Curry = require("bs-platform/lib/js/curry.js");

function map(f, res) {
  if (res.tag) {
    return /* Ok */Block.__(1, [Curry._1(f, res[0])]);
  } else {
    return /* Error */Block.__(0, [res[0]]);
  }
}

function map2(f, r1, r2) {
  if (r1.tag) {
    if (r2.tag) {
      return /* Ok */Block.__(1, [Curry._2(f, r1[0], r2[0])]);
    } else {
      return /* Error */Block.__(0, [r2[0]]);
    }
  } else {
    return /* Error */Block.__(0, [r1[0]]);
  }
}

function map3(f, r1, r2, r3) {
  if (r1.tag) {
    if (r2.tag) {
      if (r3.tag) {
        return /* Ok */Block.__(1, [Curry._3(f, r1[0], r2[0], r3[0])]);
      } else {
        return /* Error */Block.__(0, [r3[0]]);
      }
    } else {
      return /* Error */Block.__(0, [r2[0]]);
    }
  } else {
    return /* Error */Block.__(0, [r1[0]]);
  }
}

function chain(f, res) {
  if (res.tag) {
    return Curry._1(f, res[0]);
  } else {
    return /* Error */Block.__(0, [res[0]]);
  }
}

function withDefault(a, res) {
  if (res.tag) {
    return res[0];
  } else {
    return a;
  }
}

function fromOption(err, opt) {
  if (opt) {
    return /* Ok */Block.__(1, [opt[0]]);
  } else {
    return /* Error */Block.__(0, [err]);
  }
}

function toOption(res) {
  if (res.tag) {
    return /* Some */[res[0]];
  } else {
    return /* None */0;
  }
}

function isError(res) {
  if (res.tag) {
    return /* false */0;
  } else {
    return /* true */1;
  }
}

function isOk(res) {
  if (res.tag) {
    return /* true */1;
  } else {
    return /* false */0;
  }
}

var bind = chain;

exports.map         = map;
exports.map2        = map2;
exports.map3        = map3;
exports.chain       = chain;
exports.bind        = bind;
exports.withDefault = withDefault;
exports.fromOption  = fromOption;
exports.toOption    = toOption;
exports.isError     = isError;
exports.isOk        = isOk;
/* No side effect */
