// Generated by BUCKLESCRIPT VERSION 2.0.0, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");

function make(create, fail, success) {
  return Curry._2(create, fail, success);
}

function succeed(a) {
  return (function (_, param) {
      return Curry._1(param, a);
    });
}

function fail(x) {
  return (function (param, _) {
      return Curry._1(param, x);
    });
}

function fork(fail, success, task) {
  return Curry._2(task, fail, success);
}

function map(f, task) {
  return (function (param, param$1) {
      return Curry._2(task, param, (function (x) {
                    return Curry._1(param$1, Curry._1(f, x));
                  }));
    });
}

function map2(f, t1, t2) {
  return (function (param, param$1) {
      return Curry._2(t1, param, (function (a1) {
                    return Curry._2(t2, param, (function (a2) {
                                  return Curry._1(param$1, Curry._2(f, a1, a2));
                                }));
                  }));
    });
}

function map3(f, t1, t2, t3) {
  return (function (param, param$1) {
      return Curry._2(t1, param, (function (a1) {
                    return Curry._2(t2, param, (function (a2) {
                                  return Curry._2(t3, param, (function (a3) {
                                                return Curry._1(param$1, Curry._3(f, a1, a2, a3));
                                              }));
                                }));
                  }));
    });
}

function flatMap(f, task) {
  return (function (param, param$1) {
      return Curry._2(task, param, (function (x) {
                    return Curry._3(f, x, param, param$1);
                  }));
    });
}

function biMap(mapFail, mapSuccess, task) {
  return (function (param, param$1) {
      return Curry._2(task, (function (err) {
                    return Curry._1(param, Curry._1(mapFail, err));
                  }), (function (ok) {
                    return Curry._1(param$1, Curry._1(mapSuccess, ok));
                  }));
    });
}

function fold(mapFail, mapSuccess, task) {
  return (function (_, param) {
      return Curry._2(task, (function (err) {
                    return Curry._1(param, Curry._1(mapFail, err));
                  }), (function (ok) {
                    return Curry._1(param, Curry._1(mapSuccess, ok));
                  }));
    });
}

function fromLazyPromise(f) {
  return (function (param, param$1) {
      Curry._1(f, /* () */0).then(param$1, param);
      return /* () */0;
    });
}

function fromOption(err, opt) {
  if (opt) {
    var a = opt[0];
    return (function (_, param) {
        return Curry._1(param, a);
      });
  } else {
    return (function (param, _) {
        return Curry._1(param, err);
      });
  }
}

function fromResult(res) {
  if (res.tag) {
    var a = res[0];
    return (function (_, param) {
        return Curry._1(param, a);
      });
  } else {
    var x = res[0];
    return (function (param, _) {
        return Curry._1(param, x);
      });
  }
}

exports.make            = make;
exports.succeed         = succeed;
exports.fail            = fail;
exports.fork            = fork;
exports.map             = map;
exports.map2            = map2;
exports.map3            = map3;
exports.flatMap         = flatMap;
exports.biMap           = biMap;
exports.fold            = fold;
exports.fromLazyPromise = fromLazyPromise;
exports.fromOption      = fromOption;
exports.fromResult      = fromResult;
/* No side effect */
